-- find total customemers by countries

select
country,
count(customer_key) as total_customers
from gold.dim_customers
group by country
order by count(customer_key) desc

-- find total customer by gender

select
gender,
count(customer_key) as total_customers
from gold.dim_customers
group by gender
order by count(customer_key) desc

-- find total products by category

select
category,
count(product_key) as total_product
from gold.dim_products
group by category
order by count(product_key) desc

-- what is the average costs in each category

select
category,
avg(cost) as avg_cost
from gold.dim_products
group by category
order by avg(cost) desc

-- what is total revenue is generated by each category

select
p.category,
sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_products p
on f.product_key = p.product_key
group by p.category
order by total_revenue desc

-- what is total revenue is generated by each customers?

select
c.customer_key,
c.first_name,
c.last_name,
sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key = c.customer_key
group by 
c.customer_key,
c.first_name,
c.last_name
order by total_revenue desc

-- what is distribution of sold items across countries?

select
c.country,
sum(f.quantity) as total_item_sold
from gold.fact_sales f
left join gold.dim_customers c
on c.customer_key = f.customer_key
group by 
c.country
order by total_item_sold desc
